version: '3.8'

services:
  manager:
    image: knplabs/server-side-renderer:manager-dev
    build:
      context: .
      target: dev
    depends_on:
      - redis
    env_file: .env
    ports:
      - "80:8080"
    volumes:
      - ./:/app

  redis:
    image: redis:6.2.2-buster

  nginx:
    image: nginx:1.20.0
    volumes:
      - ./fixtures/nginx/html:/usr/share/nginx/html:ro

  test:
    image: knplabs/server-side-renderer:test-runner-dev
    build:
      context: .
      target: dev
    command: yarn test
    volumes:
      - ./:/app
    profiles:
      - test
